providers = ["php"]

[phases.setup]
  nixPkgs = ["nodejs_22"]

[phases.install]
  cmds = [
    "sudo apt-get update && sudo apt-get install -y --no-install-recommends php-cli composer",
    "npm install",
    "composer install --no-dev --optimize-autoloader --no-interaction"
  ]

[phases.build]
  cmds = [
    "npm run build"
  ]
